### ISSUE TITLE
Wrong upgrade regexp

### ISSUE THREAD

**Issue by cyborgshead** [regen-network/cosmosd#14]
We are in cyber~Congress researching upgrades functionality and found that cosmosd doesn't automatically migrate to new binary when needed

For example, the node produces this output when triggered upgrade (proposal with empty plan info):
```
UPGRADE "euler-8" NEEDED at height: 16000:
```

And cosmosd doesn't upgrade and relink to new binary because scanner doesn't match upgrade string with current regexp:
```
UPGRADE "(.*)" NEEDED at height (\d+):\s+([^\s]*)
```
But with following regexp all things done:
```
UPGRADE "(.*)" NEEDED at height: (\d+):\s+([^\s]*)
```

__plan.DueAt() returns height: block_number__
https://github.com/cosmos/cosmos-sdk/blob/release/v0.38.2/x/upgrade/abci.go#L38
https://github.com/cosmos/cosmos-sdk/blob/release/v0.38.2/x/upgrade/internal/types/plan.go#L77

Note: cosmos-sdk 0.38.{1,2}

@ethanfrey @aaronc

**Comment by ethanfrey** [comment]
Good catch. @anilCSE did people have such errors in the regen testnet? Or did this work?

Before changing, I want to figure if we change cosmosd or cosmos-SDK

**Comment by anilcse** [comment]
Haven't tested it myself on current testnet but looks like there's this issue. I tried a local testnet upgrade and it didn't work. Good catch @litvintech .
Not sure on when/why it was changed, it worked for 0.34 smoothly (Regen's algradigon testnet). May be latest upgrade module work (cosmos-sdk) has these changes. I didn't find a commit yet.

btw, @ethanfrey how we gonna handle this case? https://github.com/cosmos/cosmos-sdk/blob/release/v0.38.2/x/upgrade/internal/types/plan.go#L74-L76
Looks like the scanner regex is not handling this case too.

**Comment by anilcse** [comment]
This didn't change in upgrade module too.
https://github.com/cosmos/cosmos-sdk/commit/d81d46192a0c26a4ed8bec911813b3239c14a55e#diff-90f3583e866435fb4e9e4cf8df66babeR71-R76

**Comment by ethanfrey** [comment]
Yup, looked like this changed in mainline. We need to modify `cosmosd`. And ideally add some integration tests (but that would be quite complex)

**Comment by anilcse** [comment]
Yes, integration tests would be complex. For now may be we can jsut fix regex and test.

**Comment by ethanfrey** [comment]
I am working on a PR for this now.
