### ISSUE TITLE
Add version  check function to cosmosd

### ISSUE THREAD

**Issue by mrlp4** [regen-network/cosmosd#16]
It would be great, if cosmosd will respond to command `cosmosd version` with release version or git commit version.

**Comment by aaronc** [comment]
Thanks for the suggestion @mrlp4 !

`cosmosd` has been [incorporated into the Cosmos SDK](https://github.com/cosmos/cosmos-sdk/pull/6820) and renamed `cosmovisor`, see: https://github.com/cosmos/cosmos-sdk/tree/master/cosmovisor

Please feel free to reopen this issue there: https://github.com/cosmos/cosmos-sdk/issues/new/choose

I would note that `cosmovisor` delegates all commands to the sub-process, but maybe for `version` we can add some extra output for the `cosmovisor` version.
