### ISSUE TITLE
DAEMON_RESTART_AFTER_UPGRADE should only restart when there is an upgrade

### ISSUE THREAD

**Issue by aaronc** [regen-network/cosmosd#8]
With DAEMON_RESTART_AFTER_UPGRADE, the upgrade manager will continue restarting the child process whenever the exit code is 0. It should only restart when there is an actual upgrade. For instance if I call a command other than `start`, like `unsafe-reset-all` that has a 0 exit code, that shouldn't restart. This is because `LaunchProcess` only returns `error`, it should probably return `(err error, doUpgrade bool)` and there's only a restart when `doUpgrade == true`.

**Comment by ethanfrey** [comment]
Ahhh.... that is an interesting, un-intended consequence.
Will make it clearer.

But `error` should always be second return value. Maybe `(restart bool, err error)`?

**Comment by ethanfrey** [comment]
Relevant code: https://github.com/regen-network/cosmosd/blob/8d8b8dd4fc182be85600a189fce237f1f9f1cf2a/process.go#L39-L48
and https://github.com/regen-network/cosmosd/blob/8d8b8dd4fc182be85600a189fce237f1f9f1cf2a/main.go#L24-L27

Please make a branch on https://github.com/regen-friends/cosmosd and PR it to https://github.com/regen-network/cosmosd master branch
