### ISSUE TITLE
current should get symlinked to genesis as well

### ISSUE THREAD

**Issue by aaronc** [regen-network/cosmosd#9]
Currently symlinking to `current` only happens for upgrades not genesis, it should happen for both.

**Comment by ethanfrey** [comment]
Okay, so don't just return path, but write this to the filesystem as well.
I tried to make some functions not mutate state for easier testabililty, but easy enough to fix this

**Comment by ethanfrey** [comment]
Work can be done in a branch on https://github.com/regen-friends/cosmosd submitted as a PR onto https://github.com/regen-network/cosmosd

**Comment by ethanfrey** [comment]
Relevant code: https://github.com/regen-network/cosmosd/blob/8d8b8dd4fc182be85600a189fce237f1f9f1cf2a/args.go#L47-L69

Behavior should be that if current is not present, make a symlink to genesis.
Return value should be the same as present, but it will change the on-disk representation on first startup.
